version: 2.1
workflows:
   workflow:
      jobs:
         - hello
         - install
jobs:
   hello:
      docker: 
         - image: cimg/node:14.10.1
      steps:
         - checkout
         - run: "echo Hello"
   install:
       docker: 
         - image: cimg/node:14.10.1
       steps:
          - checkout
          - restore_cache:
              key: yarn-packages-{{ checksum "yarn.lock" }}
