version: 2.1
workflows:
   workflow:
      jobs:
         - hello
         - install
         - prettyfy
jobs:
   hello:
      docker: 
         - image: cimg/node:14.10.1
      steps:
         - checkout
         - run: "echo Hello"
   install:
       docker: 
         - image: cimg/node:14.10.1
       steps:
          - checkout
          - restore_cache:
              key: yarn-packages-{{ checksum "yarn.lock" }}
          - run: yarn global add node-gyp && yarn install
          - save_cache:
              key: yarn-packages-{{ checksum "yarn.lock" }}
              paths:
                - ./node_modules
   prettyfy:
      docker: 
         - image: cimg/node:14.10.1
      steps:
          - checkout
          - restore_cache:
             key: yarn-packages-{{ checksum "yarn.lock" }}
          - run: yarn lint && yarn format:check
          - save_cache:
              key: yarn-packages-{{ checksum "yarn.lock" }}
              paths:
                - ./node_modules
